apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service-via-argocd
spec:
  type: ClusterIP
  selector:
    app: nginx
  sessionAffinity: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
